- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
1. Обновила Target и Compile Sdk
2. Обновила версии у существующих библиотек
3. Добавила новые библиотеки: Glide, Gson, Room, Retrofit, OkHttp, Koin, AndroidX Navigation, AndroidX Activity, AndroidX Fragment
> HH-1: Обновляет Gradle. Добавляет необходимые библиотеки

- app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
- app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
- app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
- app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
- app/src/main/java/ru/practicum/android/diploma/features/root/HHApplication.kt
Добавил интерсептор для того, чтобы к каждому запросу автоматом добавлялся заголовок с токеном авторизации.
Не нужно в каждом запросе писать заголовок в ручную, интерсептор перехватит и сам вставит.
> HH-5: Добавляет di и interceptor для заголовка запросов

- app/src/main/java/ru/practicum/android/diploma/features/root/RootActivity.kt
- app/src/main/res/layout/fragment_favourite_vacancies.xml
- app/src/main/res/layout/fragment_team_info.xml
- app/src/main/res/values-en/strings.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Реализовала верстку экрана Изборанное
Также изменили в стилях текст на 22sp, название не меняла - заведу отдельную задачу на это
В экране команды - убрала лишний margin и прожала opt+cmd+l 
В recyclerView добавила коммент - надо открыть, когда появится item для вакансии.
> HH-35: реализует верстку экрана Избранное

- app/src/main/java/ru/practicum/android/diploma/features/common/presentation/recycler/VacancyViewHolder.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/recycler/VacancyViewHolder.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
- app/src/main/res/layout/fragment_search.xml
Добавили такую возможность из-за стейтов ошибок. Например у нас выполнился запрос при стейте контент - список показывается, чтобы повторно не отправлять запрос мы блокируем одинаковый параметр запроса. Однако, если у нас запрос был отправлен при каком-то стейте ошибки, то нам нужно ещё раз отправить, уже через кнопку.
> HH-62: Добавляет возможность запуска поиска через клавиатуру

- app/src/main/java/ru/practicum/android/diploma/features/common/data/database/FavouritesDao.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/data/database/VacancyDbEntity.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/domain/model/VacancyDetails.kt
- app/src/main/java/ru/practicum/android/diploma/features/favourite/data/dto/VacancyDetailsDbMapper.kt
- app/src/main/java/ru/practicum/android/diploma/features/favourite/data/repository/FavouriteVacanciesRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/api/FavouriteVacanciesInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/api/FavouriteVacanciesRepository.kt
- app/src/main/java/ru/practicum/android/diploma/features/favourite/domain/interactor/FavouriteVacanciesInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/model/FavouriteVacancyUIMapper.kt
- app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/ui/FavouriteVacanciesFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/data/dto/VacancyMapToDomain.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/data/repository/VacancyDetailsRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/api/VacancyDetailsInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/api/VacancyDetailsRepository.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/domain/interactor/VacancyDetailsInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/model/VacancyInfoUI.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/model/VacancyUIMapper.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/ui/VacancyInfoFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/viewmodel/VacancyInfoViewModel.kt
- Добавила признак isFavourite, если вакансия была добавлена в избранное. 
- Добавила логикау удаления вакансии из избранного
- Убрала пустые файлы из пакета с экраном Избранное
> HH-60: Добавляет признак isFavourite, если вакансия была добавлена в избранное.  Добавляет логику удаления вакансии из избранного

- app/src/main/java/ru/practicum/android/diploma/features/common/data/database/VacancyDbEntity.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/data/network/dto/vacancy/details/DetailsVacancyEntity.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/domain/model/VacancyDetails.kt
- app/src/main/java/ru/practicum/android/diploma/features/favourite/data/dto/VacancyDetailsDbMapper.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/data/dto/VacancyMapToDomain.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/model/VacancyUIMapper.kt
- app/src/main/res/values/strings.xml
Также меняет строку при отсутствии зп на экране вакансии
> HH-106 Исправление логики экрана Вакансия

- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
> HH-103: Исправляет баг с пагинацией

- app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/CountryUI.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/LocationSelectionState.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/RegionUI.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/Regionable.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/recycler/LocationAdapter.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/recycler/LocationDiffCallback.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/recycler/LocationViewHolder.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/ui/LocationSelectionFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/view_model/LocationSelectionViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/viewmodel/LocationSelectionViewModel.kt
- app/src/main/res/layout/fragment_location_selection.xml
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/layout/item_location_selection.xml
- app/src/main/res/values-en/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- Добавлена верстка
- Добавлен вью модель
- На экране отработаны все состояния
> HH-86: реализует экран Выбор страны

- app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/AreaUI.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/CityUI.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/CountryUI.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/Regionable.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/WorkplaceLocation.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/model/WorkplaceLocationState.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/ui/WorkplaceSelectionFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/view_model/WorkplaceSelectionViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/viewmodel/WorkplaceSelectionViewModel.kt
- app/src/main/res/drawable/arrow_forward_24px.xml
- app/src/main/res/drawable/work_place_button.xml
- app/src/main/res/layout/fragment_workplace_selection.xml
- app/src/main/res/values-en/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> HH-85: Создаёт верстку экрана, Fragment, ViewModel

- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/SearchFiltersFragment.kt
- app/src/main/res/layout/fragment_search_filters.xml
- app/src/main/res/values/styles.xml
Откорректирована вёрстка.
Добавлен слушатель клика на иконку крестик, который убирает фокус и прячет клавиатуру.
> HH-122: Убирает фокус по умолчанию

- app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/repository/FilterRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/service/FilterStorage.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/domain/filter/repositoryapi/FilterRepository.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/repository/LocationRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/api/LocationInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/api/LocationRepository.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/interactor/LocationInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/model/LocationMapUIDomain.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/ui/LocationSelectionFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/viewmodel/LocationSelectionViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/ui/WorkplaceSelectionFragment.kt
- app/src/main/res/navigation/main_navigation_graph.xml
+ получает id страны через префсы
+ задействует репозиторий фильтра
> HH-126  Исправляет переходы на экраны "Выбор страны" и "Выбор региона"

- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/dto/LocationMapDataDomain.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/data/repository/LocationRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/interactor/LocationInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/domain/model/Region.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/ui/LocationSelectionFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectlocation/presentation/viewmodel/LocationSelectionViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectworkplace/presentation/ui/WorkplaceSelectionFragment.kt
- app/src/main/res/layout/fragment_workplace_selection.xml
Исправляет ошибку с получением пустого списка регионов с апишки
> HH-138: Реализует поиск по регионам

- app/src/main/java/ru/practicum/android/diploma/features/search/domain/interactor/VacanciesSearchInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/domain/interactor/VacanciesSearchInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/domain/model/QuerySearch.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/model/SearchState.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
1. Создание QuerySearch перенесено на ViewModel
2. Реализовано получение данных их Префы во ViewModel
3. Доработан QuerySearch - убраны магические числа
4. Реализован маппер на ViewModel для создания запроса
5. Реализовано отображение значка фильтра
> HH-68: Прорабатывает поисковый запрос с фильтрами

- app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/repository/FilterRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/data/filterstorage/service/FilterStorage.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/domain/filter/repositoryapi/FilterRepository.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/presentation/models/FilterUIMapper.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/FilterInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/SharedPrefInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/FilterInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/SharedPrefInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/model/FilterUI.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/SearchFiltersFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/viewmodel/SearchFilterViewModel.kt
- app/src/main/res/values/styles.xml
- Реализация логики сохранения "Уровень ЗП", "Не показывать без ЗП", "Отрасль"
> HH-73: Фильтр - Логика сохранения и применения настроек фильтра («Уровень ЗП», «Не показывать без ЗП», «Отрасль»).

- app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
- app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/data/network/api/HHApi.kt
- app/src/main/java/ru/practicum/android/diploma/features/common/data/network/service/NetworkClient.kt
- app/src/main/java/ru/practicum/android/diploma/features/favourite/presentation/ui/FavouriteVacanciesFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/data/dto/SpecializationMapDataDomain.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/data/repository/SpecializationRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/domain/api/MapToData.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/domain/api/SpecializationInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/domain/api/SpecializationRepository.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/domain/interactor/SpecializationInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/domain/model/Industry.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/model/Industries.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/model/IndustriesState.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/model/SpecializationMapUIDomain.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/ui/SpecializationSelectionFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/ui/adapter/SpecializationSelectionAdapter.kt
- app/src/main/java/ru/practicum/android/diploma/features/selectspecialization/presentation/viewmodel/SpecializationSelectionViewModel.kt
- app/src/main/res/layout/fragment_specialization_selection.xml
> HH-71: Реализует UI и логику поиска по списку отраслей

- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFiltersFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/viewmodel/SearchViewModel.kt
> HH-163: чинит баг - Экран "Поиск вакансий" - не стартует автоматом поиск

- app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/location/LocationInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/domain/api/workplace/SelectWorkplaceInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/LocationInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/domain/interactor/SelectWorkplaceInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/location/LocationSelectionViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/workplace/WorkplaceSelectionFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/workplace/WorkplaceSelectionViewModel.kt
- При удалении и замене страны удаляется регион
- Если мы уходим c экрана через жест / системную кнопку / стрелку на тулбаре - изменения не сохраняются
- В списке регионов больше нет стран из объекта "Другие регионы" который приходит с api
> HH-177: Исправляет баги на экране место работы

- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/location/LocationSelectionFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/location/LocationSelectionViewModel.kt
Также чуть-чуть причесывает код
> HH-159: Исправляет странное поведение списка при поиске региона

- app/src/main/java/ru/practicum/android/diploma/features/search/presentation/ui/SearchFragment.kt
- app/src/main/java/ru/practicum/android/diploma/features/vacancy/presentation/ui/VacancyInfoFragment.kt
ПРи возвращении с экрана детали вакансии в поиск, начинался повторный поиск.
> HH-191: Убирает повторный поиск

- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/searchfilter/SearchFiltersFragment.kt
> HH-199: Исправляет цвет hint у полей место работы и отрасль на экране фильтров

- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/specialization/SpecializationSelectionViewModel.kt
- Исправил баг повторного поиска при включении интернета
> HH-206: "Выбор отрасли" - баг поиска при отсутствии интернета

- app/src/main/java/ru/practicum/android/diploma/features/filters/presentation/ui/location/LocationSelectionViewModel.kt
- Исправил баг поиска при повторном включении интернета
> HH-209: "Выбор региона" - баг поиска при отсутствии интернета
